more fixes
beerose/graphql-engine pull request #30
Opened 2020-09-22 16:53 UTC by kolharsam

- [x] `schemaList` sql — fix, use `getRunSql`,
 - [ ] take care of `additionalColumnsInfoQuery`

2020-09-22 16:54 UTC, kolharsam commented on console/src/dataSources/services/mysql/sqlUtils.ts
> +OR schema_name = 'performance_schema') ORDER BY schema_name ASC;`;
The original rql query had the condition in order to place the nulls towards the end. Is that still necessary?

2020-09-22 22:00 UTC, beerose requested changes

2020-09-22 22:00 UTC, beerose commented on console/src/dataSources/services/mysql/sqlUtils.ts
> +  getRunSqlQuery(schemaListSQL, source);
Don't use it here. Export sql and use `getRunSqlQuery` in the place when it's needed. Same way as it's done for all other SQL utilities. we want SQL logic separated from API logic. Generating RQL queries (`getRunSqlQuery`) is an API related thing — thus it should not be here.

2020-09-22 22:00 UTC, beerose commented on console/src/dataSources/services/mysql/sqlUtils.ts
> +const schemaListSQL = `SELECT schema_name FROM information_schema.schemata WHERE
Why nested SQL? Those are some hard coded strings. Are you aware of the performance cost of this nested select? Please bring back the previous SQL.

2020-09-22 22:00 UTC, beerose commented on console/src/dataSources/services/postgresql/index.tsx
> +const schemaList = (source: string) => getRunSqlQuery(schemaListSQL, source);
```suggestion
const schemaListSql = <SQL FROM ABOVE>`
```

2020-09-22 22:03 UTC, beerose commented on console/src/dataSources/services/postgresql/index.tsx
> +const schemaListSQL = `SELECT schema_name FROM information_schema.schemata WHERE
Same thing. Please rewrite this query.

2020-09-28 12:21 UTC, beerose approved these changes

2020-09-28 12:22 UTC, merged