[wip]: add the new queries to console code
beerose/graphql-engine pull request #39
Opened 2020-10-15 10:23 UTC by kolharsam

####TODO once code here is cleaned up.

2020-10-15 11:21 UTC, kolharsam commented on console/src/components/Common/FilterQuery/FilterQuery.tsx
> +interface Props extends InjectedProps {
@beerose the props here are incorrect. This is the error that is reported: ` JSX element type 'FilterQuery' does not have any construct or call signatures.`

2020-10-15 11:22 UTC, beerose commented on console/src/components/Common/FilterQuery/FilterQuery.tsx
> +> = (state, ownProps) => ({
```suggestion
const mapStateToProps = (state: ReduxState, ownProps: ExternalProps) => ({
```

2020-10-15 11:24 UTC, beerose commented on console/src/metadata/queryUtils.ts
> +    'default',
we shouldn't pass source at all

2020-10-15 11:28 UTC, beerose requested changes

2020-10-15 11:28 UTC, beerose commented on console/src/metadata/queryUtils.ts
> +    'default',
we shouldn't pass the source. server will take care of that and will make this query on the proper source

2020-10-15 11:28 UTC, beerose commented on console/src/metadata/queryUtils.ts
> +    'default',
we shouldn't pass the source. server will take care of that and will make this query on the proper source

2020-10-15 11:28 UTC, beerose commented on console/src/metadata/queryUtils.ts
> +  }
Please remove

2020-10-15 11:28 UTC, beerose commented on console/src/metadata/queryUtils.ts
> +  noPrefix?: boolean
```suggestion
```

2020-10-15 11:28 UTC, beerose commented on console/src/components/Services/Events/Container.tsx
> +      </li>
```suggestion
```

2020-10-15 16:37 UTC, kolharsam commented
@beerose updated the description of the PR for full details on what I'm trying to do in this PR.

2020-10-21 12:46 UTC, beerose commented on console/src/components/Services/Events/Common/Components/EventsSubTable.tsx
> +const connectedEventSubTable = connector(EventsSubTable);
```suggestion
const ConnectedEventSubTable = connector(EventsSubTable);
```

This is a component.

2020-10-21 12:46 UTC, beerose commented on console/src/components/Services/Events/Common/Components/EventsSubTable.tsx
> +});
Don't use side effect in connect argument functions.

2020-10-21 17:28 UTC, beerose commented on console/src/components/Services/Data/DataPageContainer.js
> +// import { currentDriver, dataSource, useDataSource } from '../../../dataSources';
```suggestion
```

2020-10-21 17:28 UTC, beerose commented on console/src/components/Services/Data/DataSourceContainer.tsx
> +  // updateSchemaInfo,
```suggestion
```

2020-10-21 17:29 UTC, beerose approved these changes

2020-10-21 17:30 UTC, merged